# Generated by Django 4.1.7 on 2023-04-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='properties',
            field=models.ManyToManyField(blank=True, help_text='Properties of the entity', to='mainapp.property'),
        ),
    ]
